### ISSUE TITLE
使用方法

### ISSUE THREAD

**Issue by wangyijin209** [code-scan/cfwork_shortlink_text#1]
请问这个怎么使用？

`npm install -g @cloudflare/wrangler`这一段是需要在服务器运行？

**Comment by superen7527** [comment]
> 本地运行,需要nodejs和npm环境. 你也可以直接把js填写到新创建的worker里面,然后关联一下kv到shortlink这个namespace,就不需要安装nodejs/npm了.

您好，js指的是这个文件吗?
https://github.com/code-scan/cfwork_shortlink_text/blob/main/index.js
不太懂js，您的意思是整个项目只需要贴上这个js，再关联kv就好了，其他文件都是nodejs用的这里都用不上嘛
