### ISSUE TITLE
能否兼容Short Menu 的Responses

### ISSUE THREAD

**Issue by coppea** [code-scan/cfwork_shortlink_text#3]
**cfwork_shortlink_text**  的响应数据为
{"link":"https://abc.com","name":"dkfcd","type":"link"}

而Short Menu不支持name值,支持以下值
> Responses
The response received from your server must either be plain text, containg only the shortened URL, or JSON. The following JSON formats are supported by Short Menu:

>{ "shorturl" : "SHORT_URL_HERE" }
{ "shortURL" : "SHORT_URL_HERE" }
{ "short" : "SHORT_URL_HERE" }
{ "id" : "SHORT_URL_HERE" }
{ "url_short" : "SHORT_URL_HERE" }
{ "data" : { "url" : "SHORT_URL_HERE" } }
{ "message" : "ERROR_MESSAGE_HERE" }
Your API can also return an array whose first object is a dictionary conforming to one of the above formats.

[https://shortmenu.com/support/custom-services/](url)
可否将name修改为short或者shorturl或者id,已支持Short Menu

**Comment by code-scan** [comment]
可以了,我给`index.js`增加了自定义前台传过来了key的常量,可以根据自己的需求修改

```js
const admin_path = '/short_link_admin'
const api_path = '/short_api'
const url_key = 'link' // original url key
const url_name = 'name' // short code  key
```
