### ISSUE TITLE
多work问题

### ISSUE THREAD

**Issue by superen7527** [code-scan/cfwork_shortlink_text#6]
你好，使用原来配置kv名字为shortlink，部署成功访问。

然后不想数据混用，于是又新建一个kv，并且在配置文件里面修改想要的work路由和名字。结果网站错误，但是把name改成shortlink以后，理应覆盖第一个名为shortlink的服务，结果却正常运行。

又测试了第三个kv，还是不同名字的work，部署提交成功，但是网站一直是返回500状态码。而且如果改成shortlink的name会让其他work没办法正常工作。

可能表达不清楚，但是自己琢磨了好久好久(有半个月吧 还有好几次通宵修改提交测试)，实在没办法解决。也问了其他使用这个项目的人都表示不懂。看您的readme很简洁，知道您可能是不喜欢太麻烦，也没有想着打扰您。但是目前实在解决不了，如果方便的话能否指点一下。如果实在麻烦也可以不予理会，我也不太想打扰您，只是万不得已，我也能理解。

**Comment by code-scan** [comment]
不要修改shortlink的名字,直接修改wrangler.toml中的kv id应该就可以了

**Comment by superen7527** [comment]
> 

你好 为了不产生旧影响我把work全删了重新绑定。不修改name 改了kv。同时为了绑定到不同服务，我还改了route。结果原服务(进的去找不到页面)和生成的新服务(没有能用的地址)都无法再使用了。

**Comment by superen7527** [comment]
花了几个通宵晚上 已解决
